var string = [];
var output = `// ah yes, I know the script looks messy :)`;
string.push(`// you don't read it, you use it...`);
string.push(`// edit the script if you want to, you can add or remove functions`);
string.push(`var value = 0;`);
string.push(`var x, y;`);
string.push(`var key = localStorage.getItem('key') || '.';`);
string.push(`let c = document.createElement('div');`);
string.push(`c.id = 'smallMenu';`);
string.push("c.style = `");
string.push(`    background: rgba(26, 26, 26, .9);`);
string.push(`    border: 1px solid red;`);
string.push(`    box-shadow: 2.5px 2.5px green;`);
string.push(`    z-index: 2147483647;`);
string.push(`    margin: 0;`);
string.push(`    padding: 15px;`);
string.push(`    position: fixed;`);
string.push(`    top: 50%;`);
string.push(`    left: 50%;`);
string.push(`    transform: translate(-50%, -50%);`);
string.push(`    box-sizing: border-box;`);
string.push(`    color: white;`);
string.push(`    text-align: center;`);
string.push(`    width: 350px;`);
string.push(`    height: 450px;`);
string.push(`    align-items = center;`);
string.push(`    flex-direction = column;`);
string.push(`    overflow: auto;`);
string.push(`    scrollbar-width: none;`);
string.push(`    font-family: lato,Helvetica,sans-serif !important;`);
string.push("`;");
string.push(`document.body.appendChild(c);`);
string.push(`const sm = document.getElementById('smallMenu');`);
string.push(``);
string.push(`document.addEventListener('keydown', (e) => {`);
string.push(`    if (e.key === key.toUpperCase() || e.key === key.toLowerCase()) {`);
string.push(`        sm.style.display !== 'none' ? sm.style.display = 'none' : sm.style.display = 'block';`);
string.push(`    }`);
string.push(`});`);
string.push(``);
string.push(`sm.addEventListener('mousedown', (e) => {`);
string.push(`    x = e.clientX;`);
string.push(`    y = e.clientY;`);
string.push(`    value = 1;`);
string.push(`});`);
string.push(``);
string.push(`sm.addEventListener('mouseup', () => {`);
string.push(`    value = 0;`);
string.push(`});`);
string.push(``);
string.push(`document.addEventListener('mousemove', (e) => {`);
string.push(`    if (value == 1) {`);
string.push(`        const diffX = e.clientX - x;`);
string.push(`        const diffY = e.clientY - y;`);
string.push("        sm.style.left = `${sm.offsetLeft + diffX}px`;");
string.push("        sm.style.top = `${sm.offsetTop + diffY}px`;");
string.push(`        x = e.clientX;`);
string.push(`        y = e.clientY;`);
string.push(`    }`);
string.push(`});`);
string.push(``);
string.push(`function add(create, type, id, style, iH, ph, ap) {`);
string.push(`    let c = document.createElement(create);`);
string.push(`    c.type = type;`);
string.push(`    c.id = id;`);
string.push(`    c.innerHTML = iH;`);
string.push(`    c.style = style;`);
string.push(`    c.placeholder = ph;`);
string.push(`    ap.appendChild(c);`);
string.push(`}`);
string.push(``);
string.push(`add('div', '', 'title', 'font-size: 30px; font-weight: bold;', 'Modioxiom', '', sm);`);
string.push(`add('canvas', '', 'c', '', '', '', sm);`);
string.push("document.getElementById('c').outerHTML = `<canvas id='c' height='10' width='300'></canvas>`;");
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'bgT', '', 'Background image: ', '', sm);`);
string.push(`add('input', 'text', 'bgTb', 'text-align: center; width: auto;', '', 'URL of a BG image', document.getElementById('bgT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'bRT', '', 'Border radius: ', '', sm);`);
string.push(`add('input', 'number', 'bRTb', 'text-align: center; width: auto;', '', 'I suggest using 11', document.getElementById('bRT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'nLT', '', 'New logo: ', '', sm);`);
string.push(`add('input', 'text', 'nLTb', 'text-align: center; width: auto;', '', 'URL of a logo', document.getElementById('nLT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'nDT', '', 'New description: ', '', sm);`);
string.push(`add('input', 'text', 'nDTb', 'text-align: center; width: auto;', '', 'Text under the logo', document.getElementById('nDT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'sCT', '', 'Shield color: ', '', sm);`);
string.push(`add('input', 'text', 'sCTb', 'text-align: center; width: auto;', '', 'Hex/ color name/ RGB', document.getElementById('sCT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'hpCT', '', 'HP color: ', '', sm);`);
string.push(`add('input', 'text', 'hpCTb', 'text-align: center; width: auto;', '', 'Hex/ color name/ RGB', document.getElementById('hpCT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'fLT', '', 'Font link: ', '', sm);`);
string.push(`add('input', 'text', 'fLTb', 'text-align: center; width: auto;', '', 'Enter a link', document.getElementById('fLT'));`);
string.push(`add('a', '', 'fLTI', '', '', '', document.getElementById('fLT'));`);
string.push("document.getElementById('fLTI').outerHTML = `<br><a href='https://www.youtube.com/watch?v=06s079hBhmA' target='_blank'>in case you don't know how to get the font link</a>`;");
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'kpgT', '', 'Show KPG: ', '', sm);`);
string.push(`add('input', 'checkbox', 'kpgCb', 'position: relative; top: 2.5px;', '', '', document.getElementById('kpgT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push(`add('div', '', 'lCbT', '', 'Longer chatbox: ', '', sm);`);
string.push(`add('input', 'checkbox', 'lCbCb', 'position: relative; top: 2.5px;', '', '', document.getElementById('lCbT'));`);
string.push(`add('pre', '', '', '', '', '', sm);`);
string.push("add('div', '', 'real', 'font-size: 12px; font-weight: bold; color: pink;', `Press '${key}' to show or hide the menu`, '', sm);");
string.push(`restore('bgTb');`);
string.push(`restore('bRTb');`);
string.push(`restore('nLTb');`);
string.push(`restore('nDTb');`);
string.push(`restore('sCTb');`);
string.push(`restore('hpCTb');`);
string.push(`restore('fLTb');`);
string.push(`document.getElementById('lCbCb').checked = JSON.parse(localStorage.getItem('lCbCb'));`);
string.push(`document.getElementById('kpgCb').checked = JSON.parse(localStorage.getItem('kpgCb'));`);
string.push(`document.getElementById('real').addEventListener('click', (e) => {`);
string.push(`    document.addEventListener('keydown', (e) => {`);
string.push(`        key = e.key;`);
string.push("        document.getElementById('real').innerHTML = `Press '${key}' to show or hide the menu`;");
string.push(`    }, { once: true });`);
string.push(`    document.getElementById('real').innerHTML = 'Click the key rn';`);
string.push(`});`);
string.push(``);
string.push(`let ctx = document.getElementById('c').getContext('2d');`);
string.push(`ctx.strokeStyle = 'red';`);
string.push(`ctx.beginPath();`);
string.push(`ctx.moveTo(0, 6);`);
string.push(`ctx.lineTo(document.getElementById('c').width, 8);`);
string.push(`ctx.stroke();`);
string.push(``);
string.push(`function check(x) {`);
string.push(`    return x.value !== undefined && x.value !== null && x.value !== '';`);
string.push(`}`);
string.push(``);
string.push(`setInterval(() => {`);
string.push("    document.querySelector('.sc-gKclnd.bNczYf') ? (check(document.getElementById('bgTb')) ? document.querySelector('.sc-gKclnd.bNczYf').style.backgroundImage = `url(${document.getElementById('bgTb').value})` : document.querySelector('.sc-gKclnd.bNczYf').style.backgroundImage = `url(/./package/c30b27cd3f6c8d9bb236.jpg)`) : void(0);");
string.push(`    if (check(document.getElementById('bRTb')) && !isNaN(document.getElementById('bRTb').value)) {`);
string.push(`        for (let i = 0; i < document.querySelectorAll('*').length; i++) {`);
string.push(`            document.querySelectorAll('*')[i].style.borderRadius = document.getElementById('bRTb').value + 'px';`);
string.push(`            document.body.style.borderRadius = '0px';`);
string.push(`            document.querySelector('.sc-gKclnd.bNczYf') ? document.querySelector('.sc-gKclnd.bNczYf').style.borderRadius = '0px' : void(0);`);
string.push(`            document.getElementById('canvas') ? document.getElementById('canvas').style.borderRadius = '0px' : void(0);`);
string.push(`            document.querySelector('.sc-jtXEFf.evngGB') ? document.querySelector('.sc-jtXEFf.evngGB').style.borderRadius = '0px' : void(0);`);
string.push(`            document.querySelector('.sc-gEOWYS.jOUDnW') ? document.querySelector('.sc-gEOWYS.jOUDnW').style.borderRadius = '0px' : void(0);`);
string.push(`        }`);
string.push(`    } else {`);
string.push(`        for (let i = 0; i < document.querySelectorAll('*').length; i++) {`);
string.push(`            document.querySelectorAll('*')[i].style.borderRadius = '0px';`);
string.push(`        }`);
string.push(`    }`);
string.push(`    document.querySelector('.sc-fDrBGk.iGESkt') ? (check(document.getElementById('nLTb')) ? (document.querySelector('.sc-fDrBGk.iGESkt').style.height = '121px', document.querySelector('.sc-fDrBGk.iGESkt').src = document.getElementById('nLTb').value) : document.querySelector('.sc-fDrBGk.iGESkt').src = 'https://voxiom.io/package/ea55824826de52b7ccc3.png') : void(0);`);
string.push(`    document.querySelector('.sc-ccATMr.beNpci') ? (check(document.getElementById('nDTb')) ? document.querySelector('.sc-ccATMr.beNpci').innerHTML = document.getElementById('nDTb').value : document.querySelector('.sc-ccATMr.beNpci').innerHTML = 'Open Alpha Testing - Pre-Season') : void(0);`);
string.push(`    document.querySelectorAll('.sc-cBIieI.kEGFCL')[1] ? (check(document.getElementById('sCTb')) ? document.querySelectorAll('.sc-cBIieI.kEGFCL')[1].style.backgroundColor = document.getElementById('sCTb').value : document.querySelectorAll('.sc-cBIieI.kEGFCL')[1].style.backgroundColor = 'rgb(255, 185, 0)') : void(0);`);
string.push(`    document.querySelectorAll('.sc-cBIieI.kEGFCL')[3] ? (check(document.getElementById('hpCTb')) ? document.querySelectorAll('.sc-cBIieI.kEGFCL')[3].style.backgroundColor = document.getElementById('hpCTb').value : document.querySelectorAll('.sc-cBIieI.kEGFCL')[3].style.backgroundColor = 'rgb(46, 204, 113)') : void(0);`);
string.push(`    if (document.querySelector('.sc-bhnkmi.eHnkoG')) {`);
string.push(`        if (document.querySelector('.sc-bhnkmi.eHnkoG').children[0] && document.querySelector('.sc-bhnkmi.eHnkoG').children[0].children[0]) {`);
string.push(`            if (document.getElementById('lCbCb').checked) {`);
string.push("                document.querySelector('.sc-bhnkmi.eHnkoG').children[0].style.maxHeight = `${document.querySelector('.sc-jFkwbb.iCCfZB').getBoundingClientRect().top - document.querySelector('.sc-dZpvmy.hPwtWR').getBoundingClientRect().bottom}px`;");
string.push("                document.querySelector('.sc-bhnkmi.eHnkoG').children[0].children[0].style.maxHeight = `${document.querySelector('.sc-jFkwbb.iCCfZB').getBoundingClientRect().top - document.querySelector('.sc-dZpvmy.hPwtWR').getBoundingClientRect().bottom}px`;");
string.push(`            } else {`);
string.push(`                document.querySelector('.sc-bhnkmi.eHnkoG').children[0].style.maxHeight = '150px';`);
string.push(`                document.querySelector('.sc-bhnkmi.eHnkoG').children[0].children[0].style.maxHeight = '150px';`);
string.push(`            }`);
string.push(`        }`);
string.push(`    }`);
string.push(`    if ((location.href.includes('/player/') || location.href.includes('/account')) && document.querySelector('.sc-dHxrtn.ccMiHg')) {`);
string.push(`        if (document.getElementById('kpgCb').checked) {`);
string.push(`            if (document.querySelector('.sc-dHxrtn.ccMiHg').children[8] == undefined) {`);
string.push(`                let c = document.createElement('div');`);
string.push(`                c.id = 'kpg';`);
string.push(`                document.querySelector('.sc-dHxrtn.ccMiHg').appendChild(c);`);
string.push("                document.getElementById('kpg').outerHTML = `<div class='sc-bJijCA iriYGK' style='border-radius: ${document.getElementById('bRTb').value}px;'><div class='sc-hGNApp KMDEf'>KPG</div><div class='sc-dGXKLq eihCRK'>${(Number(document.querySelectorAll('.sc-dGXKLq.eihCRK')[3].innerHTML) / Number(document.querySelectorAll('.sc-dGXKLq.eihCRK')[0].innerHTML)).toFixed(2)}</div></div>`;");
string.push(`            } else {`);
string.push("                document.querySelector('.sc-dHxrtn.ccMiHg').children[8].outerHTML = `<div class='sc-bJijCA iriYGK' style='border-radius: ${document.getElementById('bRTb').value}px;'><div class='sc-hGNApp KMDEf'>KPG</div><div class='sc-dGXKLq eihCRK'>${(Number(document.querySelectorAll('.sc-dGXKLq.eihCRK')[3].innerHTML) / Number(document.querySelectorAll('.sc-dGXKLq.eihCRK')[0].innerHTML)).toFixed(2)}</div></div>`;");
string.push(`            }`);
string.push(`        } else {`);
string.push(`            document.querySelector('.sc-dHxrtn.ccMiHg').children[8] ? document.querySelector('.sc-dHxrtn.ccMiHg').children[8].remove() : void(0);`);
string.push(`        }`);
string.push(`    }`);
string.push(`    store('bgTb');`);
string.push(`    store('bRTb');`);
string.push(`    store('nLTb');`);
string.push(`    store('nDTb');`);
string.push(`    store('sCTb');`);
string.push(`    store('hpCTb');`);
string.push(`    store('fLTb');`);
string.push(`    localStorage.setItem('lCbCb', document.getElementById('lCbCb').checked);`);
string.push(`    localStorage.setItem('kpgCb', document.getElementById('kpgCb').checked);`);
string.push(`    localStorage.setItem('key', key);`);
string.push(`}, 1); //speed speed speed`);
string.push(``);
string.push(`font();`);
string.push(`document.getElementById('fLTb').addEventListener('input', font);`);
string.push(``);
string.push(`function font() {`);
string.push(`    if (document.getElementById('fLTb').value !== '') {`);
string.push(`        fetch(document.getElementById('fLTb').value)`);
string.push(`            .then((r) => {`);
string.push(`                return r.text();`);
string.push(`            })`);
string.push(`            .then((d) => {`);
string.push(`                try {`);
string.push(`                    document.getElementById('style') ? document.getElementById('style').remove() : void(0);`);
string.push("                    let css = `");
string.push("                    @import url('${document.getElementById('fLTb').value}');");
string.push(`                    * {`);
string.push(`                        font-family:` + "${`${" + `d.split("font-family: '")` + `[1].split("';")` + '[0]}`} !important;');
string.push(`                    };`);
string.push(`                    #smallMenu::-webkit-scrollbar {`);
string.push(`                        width: 0px;`);
string.push(`                    }`);
string.push(`                    pre {`);
string.push(`                        height: 16.5px;`);
string.push("                    }`;");
string.push(`                    let style = document.createElement('style');`);
string.push(`                    style.id = 'style';`);
string.push(`                    style.innerHTML = css;`);
string.push(`                    document.head.appendChild(style);`);
string.push(`                } catch (error) {`);
string.push(`                    console.log(error);`);
string.push(`                }`);
string.push(`            })`);
string.push(`            .catch((e) => {`);
string.push(`                console.log(e);`);
string.push(`            })`);
string.push(`    } else {`);
string.push("        let css = `");
string.push(`        * {`);
string.push(`            font-family: lato,Helvetica,sans-serif !important;`);
string.push(`        }`);
string.push(`        #smallMenu::-webkit-scrollbar {`);
string.push(`            width: 0px;`);
string.push(`        }`);
string.push(`        pre {`);
string.push(`            height: 16.5px;`);
string.push("        }`;");
string.push(`        let style = document.createElement('style');`);
string.push(`        style.id = 'style';`);
string.push(`        style.innerHTML = css;`);
string.push(`        document.head.appendChild(style);`);
string.push(`    }`);
string.push(`}`);
string.push(``);
string.push(`function store(x) {`);
string.push(`    localStorage.setItem(x, document.getElementById(x).value);`);
string.push(`}`);
string.push(``);
string.push(`function restore(x) {`);
string.push(`    document.getElementById(x).value = localStorage.getItem(x) || '';`);
string.push(`}`);
string.forEach((s) => {
    output += `\n`;
    output += s;
});